# =============================================================================
#  code/shared/make_paper_outputs.R
#
#  PAPER REPLICATION: assembles every figure and table included in the paper,
#  with the exact file names referenced by the LaTeX source, into
#
#      output/paper_replication/
#        figures/main/                    (11 figures of the main text)
#        figures/robustness/<spec>/       (6 figures of the robustness appendix)
#        tables/                          (6 LaTeX tables)
#        paper_numbers.csv                (every scalar quoted in the text)
#
#  To compile the paper, copy output/paper_replication/figures/ next to the
#  .tex file (the LaTeX includes use the relative paths figures/main/... and
#  figures/robustness/...).
#
#  PREREQUISITES (in order; all are steps of run_all.R):
#    1. code/01_process_gpr.R, code/02_build_dataset.R          (data)
#    2. code/dralacbn/02_dralacbn_information_set_robustness.R  (main + robustness)
#    3. code/dralacbn/08_dralacbn_perfect_foresight.R           (Section 3.4)
#    4. code/dralacbn/10_dralacbn_state_dependence.R            (Section 3.3)
#  This script is idempotent and purely assembles existing outputs; the only
#  computation it performs is the derivation of in-text scalars (e.g. the
#  posterior probability of a positive peak response) from saved draws.
#
#  Every missing input is reported and skipped; the final recap lists what was
#  produced and what is still missing.
#
#  Run from the repository root:
#      source("code/shared/make_paper_outputs.R")
# =============================================================================

source("code/00_setup.R")

suppressPackageStartupMessages({
  library(data.table)
})

# -----------------------------------------------------------------------------
# 0. Output tree and helpers
# -----------------------------------------------------------------------------

REP_DIR <- file.path("output", "paper_replication")
FIG_MAIN <- file.path(REP_DIR, "figures", "main")
FIG_ROB  <- file.path(REP_DIR, "figures", "robustness")
TAB_DIR  <- file.path(REP_DIR, "tables")

for (d in c(FIG_MAIN, TAB_DIR,
            file.path(FIG_ROB, c("real_side_light", "monetary", "uncertainty")))) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

#  Clean the figure folders so stale images from earlier runs (e.g. PNGs from
#  before the switch to vector PDF, or renamed/removed figures) do not linger in
#  the committed deliverable. Tables are overwritten in place and left as is.
old_figs <- list.files(
  c(FIG_MAIN, file.path(FIG_ROB, c("real_side_light", "monetary", "uncertainty"))),
  pattern = "\\.(png|pdf)$", full.names = TRUE, ignore.case = TRUE
)
if (length(old_figs)) invisible(file.remove(old_figs))

#  Status ledger: one row per deliverable, printed in the final recap.
.status <- data.table(item = character(), status = character())
mark <- function(item, ok) {
  .status <<- rbind(.status,
                    data.table(item = item, status = if (ok) "ok" else "MISSING"))
  invisible(ok)
}

copy_fig <- function(src, dst_dir, dst_name = basename(src)) {
  ok <- file.exists(src)
  if (ok) file.copy(src, file.path(dst_dir, dst_name), overwrite = TRUE)
  mark(file.path(basename(dst_dir), dst_name), ok)
}

fmt <- function(x, d = 3) formatC(x, format = "f", digits = d)

#  Numbers ledger: every scalar quoted in the text of the paper.
.numbers <- data.table(name = character(), value = numeric())
add_number <- function(name, value) {
  .numbers <<- rbind(.numbers,
                     data.table(name = name, value = as.numeric(value)))
  invisible(value)
}

# -----------------------------------------------------------------------------
# 1. Descriptive and main-result figures (PDF, regenerated by the plot script)
# -----------------------------------------------------------------------------
#  code/plots_paper_descriptive.R renders graph_gpr, graph_e1, graph_dralacbn,
#  graph_var_irf, graph_z, graph_pd into output/paper/{pdf,png}/<series>/.

cat("\n[1/5] Descriptive and main-result figures\n")

tryCatch(
  source("code/plots_paper_descriptive.R"),
  error = function(e) message("plots_paper_descriptive.R failed: ",
                              conditionMessage(e))
)

paper_pdf <- file.path(if (exists("DIR_PAPER")) DIR_PAPER else file.path("output", "paper"), "pdf")

copy_fig(file.path(paper_pdf, "gpr", "graph_gpr.pdf"), FIG_MAIN)
copy_fig(file.path(paper_pdf, "gpr", "graph_e1.pdf"), FIG_MAIN)
copy_fig(file.path(paper_pdf, "dralacbn", "graph_dralacbn.pdf"), FIG_MAIN)
copy_fig(file.path(paper_pdf, "results", "graph_var_irf.pdf"), FIG_MAIN)
copy_fig(file.path(paper_pdf, "results", "graph_z.pdf"), FIG_MAIN)
copy_fig(file.path(paper_pdf, "results", "graph_pd.pdf"), FIG_MAIN)

# -----------------------------------------------------------------------------
# 2. Exercise figures (copied under the names used by the LaTeX source)
# -----------------------------------------------------------------------------

cat("[2/5] Exercise figures\n")

main_spec <- file.path("output", "applications", "dralacbn", "main_specification")
state_dir <- file.path("output", "applications", "dralacbn", "state_dependence")
pf_dir    <- file.path("output", "applications", "dralacbn", "perfect_foresight")
ss_bma_single <- file.path("output", "applications", "dralacbn", "short_sample",
                           "bma", "figures", "single")
dc_dir    <- file.path("output", "applications", "dralacbn", "direct_channel", "paper")

copy_fig(file.path(main_spec, "irf", "PD_VaR", "pd_var_girf_one_sd_alpha0p99.pdf"),
         FIG_MAIN, "pd_var0p99_dralacbn_real_side_1sd.pdf")
copy_fig(file.path(main_spec, "irf", "PD_VaR", "pd_mean_vs_var_one_sd.pdf"),
         FIG_MAIN, "pd_mean_vs_var_dralacbn_real_side_1sd.pdf")
copy_fig(file.path(main_spec, "irf", "PD_VaR", "pd_mean_vs_es_one_sd.pdf"),
         FIG_MAIN, "pd_mean_vs_es_dralacbn_real_side_1sd.pdf")
copy_fig(file.path("output", "review", "figures", "simulation_benchmark.pdf"),
         FIG_MAIN, "simulation_benchmark.pdf")
copy_fig(file.path(state_dir, "figures", "fig_state_dependence_inversion.pdf"), FIG_MAIN)
copy_fig(file.path(state_dir, "figures", "fig_state_dependence_curve.pdf"), FIG_MAIN)
#  Perfect-foresight trajectory figure (Section 3.4): the SHOCKED PD level path
#  along the September 11 (2001Q3) scenario, exact closed form vs the two
#  perfect-foresight variants. The bias table (tab_pf_bias.tex, regenerated from
#  the rds in section 3 below) reports the baseline expected PD level.
copy_fig(file.path(pf_dir, "figures", "fig_perfect_foresight_shocked_levels.pdf"),
         FIG_MAIN)

#  Shorter-default-histories section: per-window BMA PD responses (one-s.d.
#  shock) for the 2005 and 2015 default windows (produced by 07 -> 09).
copy_fig(file.path(ss_bma_single, "pd_girf_window_2005_1sd.pdf"), FIG_MAIN)
copy_fig(file.path(ss_bma_single, "pd_girf_window_2015_1sd.pdf"), FIG_MAIN)

#  Orthogonality / direct-channel exercise (03 -> 04): the relaxed model
#  (eta not perp u) and the lambda posterior that justifies the baseline
#  closed form. PD responses with vs without the direct channel, and the
#  posterior of the direct-channel coefficient lambda.
copy_fig(file.path(dc_dir, "figures", "fig_direct_channel_pd_girf_1sd.pdf"), FIG_MAIN)
copy_fig(file.path(dc_dir, "figures", "fig_direct_channel_lambda_posterior.pdf"), FIG_MAIN)
#  Direct-channel tables: control-function / orthogonality test and the PD
#  responses with vs without the relaxed assumption (copied as-is from 04).
copy_fig(file.path(dc_dir, "tables", "tab_direct_channel_satellite.tex"), TAB_DIR)
copy_fig(file.path(dc_dir, "tables", "tab_direct_channel_pd.tex"), TAB_DIR)

#  Robustness: pipeline folder names -> LaTeX folder names.
rob_root <- file.path("output", "robustness", "dralacbn", "information_set",
                      "by_information_set")
spec_map <- c(real_side_lighter = "real_side_light",
              monetary          = "monetary",
              uncertainty       = "uncertainty")

for (spec in names(spec_map)) {
  for (stem in c("var_irf_1sd.pdf", "pd_girf_1sd.pdf")) {
    copy_fig(file.path(rob_root, spec, "figures", stem),
             file.path(FIG_ROB, spec_map[[spec]]), stem)
  }
}

# -----------------------------------------------------------------------------
# 3. Table generators
# -----------------------------------------------------------------------------

cat("[3/5] Tables\n")

#  --- helpers ----------------------------------------------------------------

tex_open <- function(path) file(path, open = "wt")

#  Pretty satellite term names, aligned with the paper tables.
pretty_sat_term <- function(variable) {
  v <- gsub("Investment \\(p\\.c\\., log\\)", "Investment (p.c., log)", variable)
  v
}

#  Generator for the model-averaged satellite tables (Table 2 and the full
#  appendix table), built from the averaged_regression.csv of the pipeline.
write_bma_table <- function(csv_path, out_path, caption, label,
                            min_inclusion = 0, footer = list()) {
  if (!file.exists(csv_path)) return(mark(basename(out_path), FALSE))
  tab <- fread(csv_path)
  keep <- tab$term == "(Intercept)" | tab$inclusion_prob >= min_inclusion
  tab <- tab[keep]

  con <- tex_open(out_path); on.exit(close(con), add = TRUE)
  cat("\\begin{table}[!htbp]\n\\centering\n\\scriptsize\n", file = con)
  cat("\\caption{\\textbf{", caption, "}}\n", sep = "", file = con)
  cat("\\label{", label, "}\n", sep = "", file = con)
  cat("\\begin{tabular}{lcccc}\n\\toprule\n", file = con)
  cat("Variable & Coef. & Post. SD & 90\\% CI & Incl. prob. \\\\\n\\midrule\n",
      file = con)
  for (i in seq_len(nrow(tab))) {
    stars <- if (nzchar(tab$signif[i])) paste0("$^{", gsub("\\*", "*", tab$signif[i]), "}$") else ""
    cat(pretty_sat_term(tab$variable[i]), " & $",
        fmt(tab$post_mean[i], 4), stars, "$ & ",
        fmt(tab$post_sd[i], 4), " & $[",
        fmt(tab$q05[i], 4), ",\\ ", fmt(tab$q95[i], 4), "]$ & ",
        fmt(tab$inclusion_prob[i], 2), " \\\\\n",
        sep = "", file = con)
  }
  if (length(footer)) {
    cat("\\midrule\n", file = con)
    for (nm in names(footer)) {
      cat(nm, " & \\multicolumn{4}{r}{", footer[[nm]], "} \\\\\n",
          sep = "", file = con)
    }
  }
  cat("\\bottomrule\n\\end{tabular}\n", file = con)
  cat("\\begin{tablenotes}\n\\footnotesize\n", file = con)
  cat("\\item Notes: Posterior mean, standard deviation, and 90\\% credible",
      " interval of each satellite coefficient under Schwarz (BIC) model",
      " averaging. The inclusion probability is the cumulative weight of the",
      " retained models that contain the term. Stars $^{*}$/$^{**}$/$^{***}$",
      " denote a posterior probability of the coefficient sign exceeding",
      " $0.95$/$0.975$/$0.99$.\n", sep = "", file = con)
  cat("\\end{tablenotes}\n\\end{table}\n", file = con)
  mark(basename(out_path), TRUE)
}

#  --- Table: model-averaged satellite (main text, top terms) ------------------

bma_csv <- file.path("output", "model_averaging", "dralacbn",
                     "dralacbn_real_side_averaged_regression.csv")
comp_csv <- file.path("output", "robustness", "dralacbn", "information_set",
                      "information_set_comparison.csv")

footer_regZ <- list()
if (file.exists(comp_csv)) {
  comp <- fread(comp_csv)
  base <- comp[information_set == "real_side"]
  if (nrow(base) == 1L) {
    footer_regZ <- list(
      "Observations" = sprintf("%d", base$n_obs_satellite),
      "$R^2$ / adj. $R^2$" = sprintf("%.2f / %.2f", base$r2, base$adj_r2),
      "Out-of-sample $R^2$" = sprintf("%.2f", base$oos_r2)
    )
    add_number("satellite_n_obs", base$n_obs_satellite)
    add_number("satellite_r2", base$r2)
    add_number("satellite_oos_r2", base$oos_r2)
  }
}

write_bma_table(
  csv_path = bma_csv,
  out_path = file.path(TAB_DIR, "tab_regZ.tex"),
  caption = "Model-averaged satellite for the systematic factor $Z$.",
  label = "tab:regZ",
  min_inclusion = 0.30,
  footer = footer_regZ
)

#  --- Table: full model-averaged satellite (appendix) -------------------------

write_bma_table(
  csv_path = bma_csv,
  out_path = file.path(TAB_DIR, "tab_dralacbn_real_side_bma_satellite.tex"),
  caption = "DRALACBN: full model-averaged satellite regression, real-side information set.",
  label = "tab:dralacbn_real_side_bma_satellite",
  min_inclusion = 0
)

#  --- Table: geopolitical episodes and state dependence -----------------------

state_rds <- file.path(state_dir, "state_dependence_results.rds")
if (file.exists(state_rds)) {
  st <- readRDS(state_rds)
  s <- as.data.table(st$summary)

  con <- tex_open(file.path(TAB_DIR, "tab_state_dependence.tex"))
  cat("\\begin{table}[!htbp]\n\\centering\n\\scriptsize\n", file = con)
  cat("\\caption{\\textbf{Geopolitical episodes evaluated at their own initial conditions.}}\n", file = con)
  cat("\\label{tab:state_dependence}\n", file = con)
  cat("\\begin{tabular}{lccccc}\n\\toprule\n", file = con)
  cat("Episode & \\makecell{PD at shock\\\\date (pp)} & \\makecell{Shock\\\\(s.d.)}",
      " & \\makecell{Peak $\\Delta$PD,\\\\own shock (pp)}",
      " & \\makecell{Peak $\\Delta$PD,\\\\1 s.d. (pp)} & Ratio \\\\\n\\midrule\n",
      sep = "", file = con)
  for (i in seq_len(nrow(s))) {
    own <- if (is.finite(s$peak_own_pp[i])) {
      sprintf("\\makecell{$%s$\\\\{\\scriptsize $[%s,\\,%s]$}}",
              fmt(s$peak_own_pp[i]), fmt(s$peak_own_lo68[i]), fmt(s$peak_own_hi68[i]))
    } else "--"
    shock <- if (is.finite(s$own_shock_sd[i])) fmt(s$own_shock_sd[i], 2) else "--"
    cat(s$state[i], " & ", fmt(s$pd0_median_pp[i], 2), " & ", shock, " & ",
        own, " & ", fmt(s$peak_1sd_pp[i]), " & ",
        fmt(s$amplification_vs_current[i], 2), " \\\\\n",
        sep = "", file = con)
  }
  cat("\\bottomrule\n\\end{tabular}\n", file = con)
  cat("\\begin{tablenotes}\n\\footnotesize\n", file = con)
  cat("\\item Notes: Generalized responses of the portfolio PD evaluated",
      " conditional on the history preceding each episode, on identical",
      " posterior draws. ``PD at shock date'' is the posterior median of the",
      " model-implied baseline PD at $h=0$. ``Own shock'' replays the",
      " episode's standardized reduced-form GPR innovation; brackets report",
      " 68\\% credible intervals. ``1 s.d.'' applies a common",
      " one-standard-deviation innovation. ``Ratio'' is the corresponding",
      " peak relative to the end-of-sample state. Parameters are full-sample",
      " estimates.\n", sep = "", file = con)
  cat("\\end{tablenotes}\n\\end{table}\n", file = con)
  close(con)
  mark("tab_state_dependence.tex", TRUE)

  #  In-text numbers: episodes, paired comparison, curve range.
  for (i in seq_len(nrow(s))) {
    key <- gsub("[^a-z0-9]+", "_", tolower(s$state[i]))
    add_number(paste0("episode_", key, "_pd0_pp"), s$pd0_median_pp[i])
    add_number(paste0("episode_", key, "_shock_sd"), s$own_shock_sd[i])
    add_number(paste0("episode_", key, "_peak_own_pp"), s$peak_own_pp[i])
    add_number(paste0("episode_", key, "_peak_1sd_pp"), s$peak_1sd_pp[i])
    add_number(paste0("episode_", key, "_ratio"), s$amplification_vs_current[i])
  }
  if (!is.null(st$prob_gulf_gt_911)) {
    add_number("prob_gulf_exceeds_september11_h3",
               st$prob_gulf_gt_911[horizon == 3, prob_gulf_greater])
  }
  cv <- as.data.table(st$curve)
  add_number("curve_peak_min_pp", min(cv$peak_dpd_pp))
  add_number("curve_peak_max_pp", max(cv$peak_dpd_pp))
  add_number("curve_peak_ratio", max(cv$peak_dpd_pp) / min(cv$peak_dpd_pp))
} else {
  mark("tab_state_dependence.tex", FALSE)
}

#  --- Table: the cost of perfect foresight ------------------------------------

pf_rds <- file.path(pf_dir, "perfect_foresight_results.rds")
if (file.exists(pf_rds)) {
  pf <- readRDS(pf_rds)
  lev <- as.data.table(pf$level_bias)
  gb  <- as.data.table(pf$girf_bias)

  con <- tex_open(file.path(TAB_DIR, "tab_pf_bias.tex"))
  cat("\\begin{table}[!htbp]\n\\centering\n\\scriptsize\n", file = con)
  cat("\\caption{\\textbf{The cost of perfect foresight: PD levels and responses.}}\n", file = con)
  cat("\\label{tab:pf_bias}\n", file = con)
  cat("\\begin{tabular}{llccccc}\n\\toprule\n", file = con)
  cat(" & & Exact & PF & Plug-in & Bias PF (\\%) & Bias plug-in (\\%) \\\\\n\\midrule\n", file = con)
  for (hh in c(4L, 8L, 12L)) {
    r <- lev[horizon == hh]
    cat(sprintf("PD level (pp) & $h=%d$ & %s & %s & %s & $%s$ & $%s$ \\\\\n",
                hh, fmt(r$exact), fmt(r$pf_macro), fmt(r$pf_full),
                fmt(r$bias_pf_macro_pct, 1), fmt(r$bias_pf_full_pct, 1)),
        file = con)
    add_number(sprintf("pf_level_bias_pf_h%d_pct", hh), r$bias_pf_macro_pct)
    add_number(sprintf("pf_level_bias_plugin_h%d_pct", hh), r$bias_pf_full_pct)
  }
  cat("\\midrule\n", file = con)
  for (sh in c("one_sd", "2001Q3")) {
    sub <- gb[shock == sh]
    r <- sub[which.max(abs(exact))]
    lab <- if (sh == "one_sd") "one s.d." else "2001:Q3"
    cat(sprintf("Peak $\\Delta$PD (pp), %s & $h=%d$ & %s & %s & %s & $%s$ & $%s$ \\\\\n",
                lab, as.integer(r$horizon),
                fmt(r$exact), fmt(r$pf_macro), fmt(r$pf_full),
                fmt(r$bias_pf_macro_pct, 1), fmt(r$bias_pf_full_pct, 1)),
        file = con)
    add_number(sprintf("pf_peak_bias_plugin_%s_pct", sh), r$bias_pf_full_pct)
  }
  cat("\\bottomrule\n\\end{tabular}\n", file = con)
  cat("\\begin{tablenotes}\n\\footnotesize\n", file = con)
  cat("\\item Notes: Posterior medians are computed on identical posterior",
      " draws. The variants differ only in the predictive variance entering",
      " the closed forms. ``Exact'' is the full closed form; ``PF'' treats",
      " the macro-financial path as known but retains the satellite-error",
      " variance; ``Plug-in'' evaluates the Merton--Vasicek map at the",
      " conditional-mean path. Biases are relative to the exact variant.\n",
      sep = "", file = con)
  cat("\\end{tablenotes}\n\\end{table}\n", file = con)
  close(con)
  mark("tab_pf_bias.tex", TRUE)
} else {
  mark("tab_pf_bias.tex", FALSE)
}

#  --- Table: information-set robustness ---------------------------------------

if (file.exists(comp_csv)) {
  comp <- fread(comp_csv)
  keep_specs <- c("real_side", "real_side_lighter", "monetary", "uncertainty")
  comp <- comp[information_set %in% keep_specs]
  comp[, information_set := factor(information_set, levels = keep_specs)]
  setorder(comp, information_set)

  con <- tex_open(file.path(TAB_DIR, "tab_dralacbn_information_set_robustness.tex"))
  cat("\\begin{table}[!htbp]\n\\centering\n\\scriptsize\n", file = con)
  cat("\\caption{\\textbf{DRALACBN credit-risk responses across VAR information sets.}}\n", file = con)
  cat("\\label{tab:dralacbn_information_set_robustness}\n", file = con)
  cat("\\begin{tabular}{lcccc}\n\\toprule\n", file = con)
  cat("Information set & $k$ & Sat. $R^2$ & OOS RMSE & Peak $\\Delta$PD, one s.d. (pp) \\\\\n\\midrule\n", file = con)
  for (i in seq_len(nrow(comp))) {
    cat(comp$info_set_label[i], " & ", comp$k[i], " & ",
        fmt(comp$r2[i], 3), " & ", fmt(comp$oos_rmse[i], 4), " & $",
        fmt(100 * comp$peak_dpd_1sd[i], 3), "$ $(h=",
        as.integer(comp$peak_h_1sd[i]), ")$ \\\\\n",
        sep = "", file = con)
    add_number(paste0("robust_peak_", comp$information_set[i], "_pp"),
               100 * comp$peak_dpd_1sd[i])
  }
  cat("\\bottomrule\n\\end{tabular}\n", file = con)
  cat("\\begin{tablenotes}\n\\footnotesize\n", file = con)
  cat("\\item Notes: The Merton--Vasicek systematic factor $Z$, asset",
      " correlation $\\rho$, and TTC PD are fixed within the application;",
      " only the VAR transmission mechanism and the selected satellite bridge",
      " change. Peak $\\Delta$PD is the largest posterior-median PD response",
      " to a one-standard-deviation innovation in the GPR equation, in",
      " percentage points, with the corresponding horizon in parentheses.\n",
      sep = "", file = con)
  cat("\\end{tablenotes}\n\\end{table}\n", file = con)
  close(con)
  mark("tab_dralacbn_information_set_robustness.tex", TRUE)
} else {
  mark("tab_dralacbn_information_set_robustness.tex", FALSE)
}

#  --- Table: BVAR posterior stability diagnostics -----------------------------
#  The stability CSV is produced by code/shared/var_information_set_diagnostics.R;
#  its location is searched to stay robust to layout changes.

stab_candidates <- list.files(file.path("output", "shared"),
                              pattern = "\\.csv$", recursive = TRUE,
                              full.names = TRUE)
stab_path <- NULL
for (f in stab_candidates) {
  cols <- tryCatch(names(fread(f, nrows = 0)), error = function(e) character())
  if (all(c("spec", "stable_share", "n_stable") %in% cols)) { stab_path <- f; break }
}

if (!is.null(stab_path)) {
  stab <- fread(stab_path)
  keep_specs <- c("real_side", "real_side_lighter", "monetary", "uncertainty")
  stab <- stab[spec %in% keep_specs]
  stab[, spec := factor(spec, levels = keep_specs)]
  setorder(stab, spec)
  spec_labels <- c(real_side = "Real-side", real_side_lighter = "Real-side (lighter)",
                   monetary = "Monetary", uncertainty = "Uncertainty")

  con <- tex_open(file.path(TAB_DIR, "tab_var_stability_info_sets.tex"))
  cat("\\begin{table}[!htbp]\n\\centering\n\\scriptsize\n", file = con)
  cat("\\caption{\\textbf{Posterior stability diagnostics for the BVAR information sets.}}\n", file = con)
  cat("\\label{tab:var_stability_info_sets}\n", file = con)
  cat("\\begin{tabular}{lccccccc}\n\\toprule\n", file = con)
  cat("Spec & $k$ & $p$ & Draws & Stable share & Stable draws",
      " & $|\\lambda|_{\\max}$ median & $|\\lambda|_{\\max}$ p95 \\\\\n\\midrule\n",
      sep = "", file = con)
  for (i in seq_len(nrow(stab))) {
    cat(spec_labels[[as.character(stab$spec[i])]], " & ", stab$k[i], " & ",
        stab$p[i], " & ", format(stab$n_draws[i], big.mark = "\\,"), " & ",
        fmt(stab$stable_share[i], 4), " & ",
        format(stab$n_stable[i], big.mark = "\\,"), " & ",
        fmt(stab$lambda_max_median_stable[i], 4), " & ",
        fmt(stab$lambda_max_p95_stable[i], 4), " \\\\\n",
        sep = "", file = con)
  }
  cat("\\bottomrule\n\\end{tabular}\n", file = con)
  cat("\\begin{tablenotes}\n\\footnotesize\n", file = con)
  cat("\\item Notes: $k$ is the number of variables in the VAR, including the",
      " GPR index, and $p$ is the lag order. Stable share is the fraction of",
      " posterior draws whose companion-matrix spectral radius is strictly",
      " below one. The last two columns report the posterior median and 95th",
      " percentile of the largest-modulus eigenvalue over stable draws.\n",
      sep = "", file = con)
  cat("\\end{tablenotes}\n\\end{table}\n", file = con)
  close(con)
  mark("tab_var_stability_info_sets.tex", TRUE)
} else {
  mark("tab_var_stability_info_sets.tex", FALSE)
}

# -----------------------------------------------------------------------------
# 4. In-text numbers (paper_numbers.csv)
# -----------------------------------------------------------------------------

cat("[4/5] In-text numbers\n")

#  Merton parameters and delinquency descriptives.
zf_path <- file.path(main_spec, "zfactor_dralacbn.csv")
if (file.exists(zf_path)) {
  zf <- fread(zf_path)
  p_ttc <- zf$p_ttc[1]; rho <- zf$rho[1]
  add_number("p_ttc_pct", 100 * p_ttc)
  add_number("rho", rho)
  add_number("delinq_mean_pct", mean(zf$delinquency))
  add_number("delinq_min_pct", min(zf$delinquency))
  add_number("delinq_max_pct", max(zf$delinquency))
  #  Through-the-cycle PD-VaR levels (closed form, unconditional Z ~ N(0,1)).
  for (a in c(0.99, 0.999)) {
    lvl <- pnorm((qnorm(p_ttc) + sqrt(rho) * qnorm(a)) / sqrt(1 - rho))
    add_number(sprintf("ttc_pdvar_%s_pct", gsub("\\.", "p", as.character(a))),
               100 * lvl)
  }
}

#  Mean PD response: peak, posterior probability of a positive peak, cumulation.
pd_rds <- file.path(main_spec, "irf", "PD", "pd_girf_1sd.rds")
if (file.exists(pd_rds)) {
  pd <- readRDS(pd_rds)
  med <- pd$bands$median
  pk <- which.max(abs(med))
  add_number("peak_1sd_pp", 100 * med[pk])
  add_number("peak_1sd_h", pd$bands$horizon[pk])
  add_number("prob_positive_peak_1sd", mean(pd$draws[pk, ] > 0, na.rm = TRUE))
  add_number("cumulated_median_12q_pp", 100 * sum(med))
}

#  PD-VaR peak responses.
pdvar_csv <- file.path(main_spec, "irf", "PD_VaR", "pd_var_peaks.csv")
if (file.exists(pdvar_csv)) {
  pv <- fread(pdvar_csv)[shock == "one_sd"]
  for (i in seq_len(nrow(pv))) {
    add_number(sprintf("pdvar_%s_peak_1sd_pp",
                       gsub("\\.", "p", as.character(pv$alpha[i]))),
               100 * pv$peak_median[i])
  }
}

#  Orthogonality / direct-channel test: posterior of the direct-channel
#  coefficient lambda and its frequentist HAC diagnostic. These are the
#  numbers that justify using the baseline (lambda = 0) closed form.
dc_lam <- file.path("output", "applications", "dralacbn", "direct_channel",
                    "tables", "lambda_posterior_summary.csv")
if (file.exists(dc_lam)) {
  ls_ <- fread(dc_lam)
  add_number("lambda_mean", ls_$mean[1])
  add_number("lambda_q05", ls_$q05[1])
  add_number("lambda_q95", ls_$q95[1])
  add_number("lambda_prob_negative", ls_$prob_negative[1])
}
dc_hac <- file.path("output", "applications", "dralacbn", "direct_channel",
                    "tables", "lambda_ols_hac_diagnostic.csv")
if (file.exists(dc_hac)) {
  hd <- fread(dc_hac)
  add_number("lambda_hac_t", hd$t_value[1])
  add_number("lambda_hac_p", hd$p_value[1])
}
dc_joint <- file.path("output", "applications", "dralacbn", "direct_channel",
                      "tables", "orthogonality_joint_test.csv")
if (file.exists(dc_joint)) {
  jt <- fread(dc_joint)
  add_number("orthogonality_joint_F", jt$F_stat[1])
  add_number("orthogonality_joint_p", jt$p_value[1])
}

fwrite(.numbers, file.path(REP_DIR, "paper_numbers.csv"))
mark("paper_numbers.csv", TRUE)

# -----------------------------------------------------------------------------
# 5. Recap
# -----------------------------------------------------------------------------

cat("[5/5] Recap\n\n")
cat("Paper replication outputs in: ", REP_DIR, "\n\n", sep = "")
n_ok <- sum(.status$status == "ok")
print(.status, nrows = 100)
cat("\n", n_ok, " / ", nrow(.status), " deliverables produced.\n", sep = "")

#  A missing deliverable means the replication is incomplete: the file left in
#  output/paper_replication/ is then a stale copy from an earlier run, which is
#  exactly the failure mode a replication package must not hide. Fail loudly so
#  that run_all.R marks the step KO. Set
#      options(paper.strict_deliverables = FALSE)
#  to downgrade this to a warning when re-running the script on its own after a
#  deliberately partial pipeline.
if (n_ok < nrow(.status)) {
  missing_items <- .status[["item"]][.status[["status"]] != "ok"]
  msg <- paste0(
    nrow(.status) - n_ok, " paper deliverable(s) missing:\n  - ",
    paste(missing_items, collapse = "\n  - "),
    "\nRe-run the corresponding pipeline step (see PREREQUISITES in the header)."
  )
  if (isTRUE(getOption("paper.strict_deliverables", TRUE))) {
    stop(msg, call. = FALSE)
  } else {
    warning(msg, call. = FALSE)
  }
}

invisible(TRUE)
